name: flutter_basics
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  animated_text_kit: ^4.2.2
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  another_carousel_pro: ^1.0.2
  url_launcher: ^6.3.0
  qr_code_scanner: ^1.0.1
  avatar_glow: ^3.0.1
  local_auth: ^2.3.0
  gap: ^3.0.1
  video_player: ^2.9.2
  audioplayers: ^6.1.0
  flick_video_player: ^0.9.0
  youtube_player_flutter: ^9.1.1
  concentric_transition: ^1.0.3
  lottie: ^3.1.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  # Run command 'dart run flutter_launcher_icons'
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ace.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/ace.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/ace.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/ace.jpg"

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/ana_de_armas.jpg

    
flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/