// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5470hXPAW4bf-KXGp6jJPDhq6juupKrI',
    appId: '1:27247791155:web:ed73244adc772cb13ca746',
    messagingSenderId: '27247791155',
    projectId: 'flutter-basics-18ab6',
    authDomain: 'flutter-basics-18ab6.firebaseapp.com',
    storageBucket: 'flutter-basics-18ab6.appspot.com',
    measurementId: 'G-X7JWKKHBNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0tokdBHTv4sGk2eR0HWTjiE9CNnWof1A',
    appId: '1:27247791155:android:257256d256b737573ca746',
    messagingSenderId: '27247791155',
    projectId: 'flutter-basics-18ab6',
    storageBucket: 'flutter-basics-18ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-d_I3kG6sGERtggO28eYG3EkbXYccqUM',
    appId: '1:27247791155:ios:73af8bfc830c8f543ca746',
    messagingSenderId: '27247791155',
    projectId: 'flutter-basics-18ab6',
    storageBucket: 'flutter-basics-18ab6.appspot.com',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-d_I3kG6sGERtggO28eYG3EkbXYccqUM',
    appId: '1:27247791155:ios:73af8bfc830c8f543ca746',
    messagingSenderId: '27247791155',
    projectId: 'flutter-basics-18ab6',
    storageBucket: 'flutter-basics-18ab6.appspot.com',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5470hXPAW4bf-KXGp6jJPDhq6juupKrI',
    appId: '1:27247791155:web:b49d20e962a280703ca746',
    messagingSenderId: '27247791155',
    projectId: 'flutter-basics-18ab6',
    authDomain: 'flutter-basics-18ab6.firebaseapp.com',
    storageBucket: 'flutter-basics-18ab6.appspot.com',
    measurementId: 'G-TVJ8ETLM36',
  );
}
